#端口
#应用名称
#eureka
server:
  port: 8082
  tomcat:
    max-http-post-size: 102400000
  max-http-header-size: 102400000
spring:
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/static/
  application:
    name: courseService
  datasource:
    url: jdbc:mysql://120.27.244.91:3306/quickapp?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8
    username: root
    password: admin123
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      #初始化大小
      initialSize: 5
      #最小值
      minIdle: 5
      #最大值
      maxActive: 20
      #最大等待时间，配置获取连接等待超时，时间单位都是毫秒ms
      maxWait: 60000
      #配置间隔多久才进行一次检测，检测需要关闭的空闲连接
      timeBetweenEvictionRunsMillis: 60000
      #配置一个连接在池中最小生存的时间
      minEvictableIdleTimeMillis: 30000
  servlet:
    multipart:
      max-file-size: 512MB
      max-request-size: 25600MB
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 5秒钟发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期

mybatis:
  type-aliases-package: com.cdut.pojo

  mapper-locations: classpath:mapper/*Mapper.xml